name: Tracker
options:
  bundleIdPrefix: com.willfulapps
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    DEVELOPMENT_TEAM: 645FC5JLWY
    SWIFT_APPROACHABLE_CONCURRENCY: YES
    SWIFT_DEFAULT_ACTOR_ISOLATION: MainActor
    SWIFT_UPCOMING_FEATURE_MEMBER_IMPORT_VISIBILITY: YES

targets:
  Tracker:
    type: application
    platform: iOS
    sources:
      - Tracker
    resources:
      - path: Tracker/Model/Tracker.xcdatamodeld
        type: xcdatamodeld
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.willfulapps.Tracker
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Tracker/Info.plist
        CODE_SIGN_ENTITLEMENTS: Tracker/Tracker.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"

  TrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TrackerTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.willfulapps.TrackerTests
    dependencies:
      - target: Tracker

  TrackerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - TrackerUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.willfulapps.TrackerUITests
        TEST_TARGET_NAME: Tracker
    dependencies:
      - target: Tracker
